name: Release

on:
  push:
    branches: [ main ]
    paths:
      - 'compose-video/**'  # 只有 compose-video 目录下的文件有变更时才触发
jobs:
  publish:
    name: Publish To Github Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/gradle-build-action@v2
      - name: Publish Package
        run: ./gradlew publish
        env:
          GITHUB_PACKAGE_USER: ${{ github.actor }}
          GITHUB_PACKAGE_TOKEN: ${{ secrets.AUTH_TOKEN }}